name: Release

on:
  workflow_call:
    inputs:
      action_to_track:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout origin repo
        uses: actions/checkout@v4.1.7

      - name: Checkout this repo
        uses: dariocurr/checkout-called@v4.1.7
        with:
          path: .git/ci/

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install --disable-pip-version-check nox pyyaml

      - name: Update tags
        env:
          ACTION_TO_TRACK: ${{ inputs.action_to_track }}
        id: tags
        run: nox -f .git/ci/utils/github.py --session update_tags

      - name: Create Github release
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: ${{ steps.tags.outputs.tag }}
