name: validate Dockerfile

on:
  workflow_call:
    inputs:
      dockerfile:
        description: path to `Dockerfile`
        required: true
        type: string
      from:
        description: origin branch
        required: false
        type: string
      to:
        description: target branch
        required: false
        type: string

jobs:
  validate:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: build Dockerfile in ${{ inputs.dockerfile }}
        uses: docker/build-push-action@master
        with:
          push: false
          file: ${{ inputs.dockerfile }}

  merge:
    needs: validate
    if: ${{ inputs.from }} && ${{ inputs.to }}
    runs-on: ubuntu-latest
    steps:
      - name: merge ${{ inputs.from }} in ${{ inputs.to }} branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ inputs.from }}
          target_branch: ${{ inputs.to }}
          github_token: ${{ github.token }}
          message: merging ${{ inputs.from }} into ${{ inputs.to }} using github actions
